final translateToPt = {
  "acaraje": "acarajé",
  "acorda": "açorda",
  "acorn_noodle_soup": "sopa de bola",
  "acquacotta": "acquacotta",
  "adobo": "adobo",
  "afelia": "afelia",
  "afghani_burger": "hambúrguer afegão",
  "agedashi_dofu": "agedashi-dofu",
  "aguachile": "aguachile",
  "agwi_jjim": "agwi jjim",
  "ais_kacang": "sorvete de amendoim",
  "ajapsandali": "ajapsandali",
  "ajoblanco": "ajoblanco",
  "akple": "akple",
  "al_pastor": "tacos al pastor",
  "aligot": "aligot",
  "alinazik_kebab": "alinazik kebab",
  "alloco": "alloco",
  "almond_biscuit": "biscoito de amêndoa",
  "aloo_gobi": "aloo Gobi",
  "aloo_paratha": "aloo paratha",
  "amala": "amala",
  "amanatto": "amanato",
  "amandine": "amêndoa",
  "ambelopoulia": "ambelopoulia",
  "ambrosia": "ambrosia",
  "ambrosia_food": "comida de ambrosia",
  "ambuyat": "ambuyat",
  "american_chop_suey": "chop suey americano",
  "american_fried_rice": "arroz frito americano",
  "american_goulash": "goulash americano",
  "ammonia_cookie": "biscoito de amônia",
  "amok_trey": "amok trey",
  "anadama_bread": "pão anadama",
  "anarsa": "anarsa",
  "andouille": "andouille",
  "andouillette": "andouillette",
  "angel_food_cake": "bolo de anjo",
  "angel_wings": "asas de anjo",
  "anju": "anju",
  "ankimo": "anquimó",
  "annin_tofu": "annin tofu",
  "anpan": "anpan",
  "ants_climbing_a_tree": "ants climbing a tree",
  "apple": "maçã",
  "apple_braeburn": "maçã braeburn",
  "apple_cake": "bolo de maçã",
  "apple_crimson_snow": "maçã crimson snow",
  "apple_crisp": "maçã desidratada",
  "apple_dumpling": "bolinho de maçã",
  "apple_golden": "maçã dourada",
  "apple_granny_smith": "maçã granny smith",
  "apple_pie": "torta de maçã",
  "apple_pink_lady": "maçã pink lady",
  "apple_red": "maçã vermelha",
  "apple_red_delicious": "maçã red delicious",
  "apple_red_yellow": "maçã vermelha amarela",
  "apple_strudel": "strudel de maçã",
  "apple_turnover": "apple turnover",
  "applesauce": "molho de maçã",
  "applesauce_cake": "bolo de maçã",
  "apricot": "damasco",
  "arancini": "arancini",
  "arbroath_smokie": "arbroath smokie",
  "arctic_roll": "arctic roll",
  "arisa_pitha": "arisa pitha",
  "arizona_cheese_crisp": "crocante de queijo arizona",
  "arros_negre": "arroz preto",
  "arrosticini": "arrosticini",
  "arroz_a_la_cubana": "arroz à cubana",
  "arroz_chaufa": "arroz chaufa",
  "arroz_con_pollo": "arroz com frango",
  "asam_pedas": "asam pedas",
  "ash_reshteh": "Ash reshteh",
  "asida": "asida",
  "asinan": "asinan",
  "aspic": "aspic",
  "assidat_zgougou": "assidat zgougou",
  "attieke": "attieke",
  "avgolemono": "avgolemono",
  "avocado": "abacate",
  "avocado_ripe": "abacate maduro",
  "ayam_bakar": "Frango grelhado",
  "ayam_goreng": "frango frito",
  "ayam_masak_merah": "frango cozido vermelho",
  "azerbaijani_pakhlava": "pakhlava do azerbaijão",
  "baba_ghanoush": "baba ghanoush",
  "babi_panggang": "porco assado",
  "babka": "babka",
  "baby_back_ribs": "baby back ribs",
  "bacalhau": "bacalhau",
  "bacalhau_a_bras": "bacalhau a bras",
  "bacalhau_a_gomes_de_sa": "bacalhau a gomes de sa",
  "bacalhau_a_ze_do_pipo": "bacalhau a ze do pipo",
  "bacalhau_com_natas": "bacalhau com natas",
  "bacalhau_com_todos": "bacalhau com todos",
  "baccala_alla_lucana": "bacalhau à lucana",
  "bacon": "bacon",
  "bacon_and_eggs": "bacon e ovos",
  "bacon_lettuce_tomato_sandwich": "sanduíche de tomate alface e bacon",
  "baeckeoffe": "baeckeoffe",
  "baek_kimchi": "baek kimchi",
  "bagel_dog": "bagel dog",
  "baghali_ghatogh": "baghali ghatogh",
  "baghrir": "baghrir",
  "bagnun": "bagnun",
  "baji": "baji",
  "bak_kut_teh": "bak kut teh",
  "bakarkhani": "bakarkhani",
  "baked_alaska": "Alasca assado",
  "baked_potato": "batata assada",
  "bakewell_tart": "torta assada",
  "bakkwa": "bakkwa",
  "baklava": "baklava",
  "bakso": "bakso",
  "bakwan": "bakwan",
  "balchao": "balchao",
  "balkenbrij": "balkenbrij",
  "balushahi": "balushahi",
  "bambalouni": "bambalouni",
  "bamischijf": "bamischijf",
  "banana": "banana",
  "banana_lady_finger": "banana lady finger",
  "banana_pudding": "pudim de banana",
  "banana_red": "banana vermelha",
  "banana_split": "banana split",
  "bananas_foster": "banana foster",
  "banga": "banga",
  "banh_bao": "banh bao",
  "banh_beo": "banh beo",
  "banh_bot_loc": "banh bot loc",
  "banh_canh": "banh canh",
  "banh_chung": "banh chung",
  "banh_cuon": "banh cuon",
  "banh_xeo": "banh xeo",
  "banitsa": "banitsa",
  "banmian": "banmian",
  "banoffee_pie": "banoffee pie",
  "baodu": "baodu",
  "baozi": "baozi",
  "bara_brith": "bara brith",
  "barbacoa": "barbacoa",
  "barbecued_spareribs": "costelas grelhadas",
  "barbecued_wing": "asa de frango",
  "barfi": "barfi",
  "barm_cake": "barm cake",
  "barmbrack": "barmbrack",
  "basbousa": "basbousa",
  "basundi": "basundi",
  "bath_bun": "bath bun",
  "bavarian_cream": "creme bávaro",
  "bazin": "bazin",
  "bean": "feijão",
  "bean_pie": "torta de feijão",
  "bear_claw": "bear claw",
  "beaten_biscuit": "beaten biscuit",
  "bedfordshire_clanger": "bedfordshire clanger",
  "beef_ball": "almôndega",
  "beef_bourguignon": "bife bourguignon",
  "beef_carpaccio": "carpaccio de carne",
  "beef_chow_fun": "bife chow fun",
  "beef_manhattan": "bife manhattan",
  "beef_noodle_soup": "sopa de macarrão de carne",
  "beef_on_weck": "carne de vaca",
  "beef_stroganoff": "strogonoff de carne",
  "beef_tartare": "bife tartare",
  "beef_wellington": "bife wellington",
  "beet_salad": "salada de beterraba",
  "beetroot": "beterraba",
  "beggars_chicken": "beggars chicken",
  "beignet": "beignet",
  "bento": "bentô",
  "beondegi": "beondegi",
  "berliner": "berliner",
  "beshbarmak": "beshbarmak",
  "beys_soup": "beys soup",
  "bhaji": "bhaji",
  "bhakri": "bhakri",
  "biangbiang_noodles": "macarrão biang biang",
  "bibikkan": "bibikkan",
  "bibimbap": "bibimbap",
  "bibingka": "bibingka",
  "bienenstich": "bienenstich",
  "bife_a_cavalo": "bife a cavalo",
  "bing": "bing",
  "bint_al_sahn": "bint al sahn",
  "bionico": "biónico",
  "birria": "birria",
  "biryani": "Biryani",
  "biscuits_and_gravy": "biscuits and gravy",
  "bisque": "bisque",
  "bistek": "bisteca",
  "blaa": "blaa",
  "black_and_white_cookie": "biscoito preto e branco",
  "black_bottom_pie": "black bottom pie",
  "black_forest_gateau": "bolo floresta negra",
  "black_pepper_crab": "black pepper crab",
  "black_pudding": "black pudding",
  "black_sesame_soup": "sopa de gergelim preto",
  "blackberry_pie": "torta de amora",
  "blancmange": "manjericão",
  "blodpalt": "palito de sangue",
  "blondie": "blondie",
  "blt": "blt",
  "blueberry": "mirtilo",
  "blueberry_pie": "torta de mirtilo",
  "bo_7_mon": "bo 7 mon",
  "bo_luc_lac": "bo luc lac",
  "bo_nuong_la_lot": "bo nuong la lot",
  "boat_noodles": "boat noodles",
  "bob_andy_pie": "bob andy pie",
  "bob_chorba": "bob chorba",
  "boeber": "boeber",
  "boerewors": "boerewors",
  "boiled_egg": "ovo cozido",
  "bolani": "bolani",
  "bolillo": "bolillo",
  "bolo_de_arroz": "bolo de arroz",
  "bolo_de_mel": "bolo de mel",
  "bolo_do_caco": "bolo do caco",
  "bologna_sandwich": "sanduíche de mortadela",
  "bologna_sausage": "salsicha de bolonha",
  "bombay_mix": "bombay mix",
  "bon_bon_chicken": "frango bon bon",
  "bonus_jack": "bonus jack",
  "bookbinder_soup": "bookbinder soup",
  "boondi": "boondi",
  "boortsog": "boortsog",
  "booyah": "booyah",
  "borek": "borek",
  "borlengo": "borlengo",
  "borscht": "borscht",
  "bossam": "bossam",
  "boston_baked_beans": "boston baked beans",
  "boston_cream_doughnut": "boston cream donuts",
  "boston_cream_pie": "boston cream pie",
  "botifarra": "botifarra",
  "botok": "botok",
  "boudin": "boudin",
  "bougatsa": "bougatsa",
  "bouillabaisse": "bouillabaisse",
  "boxty": "boxy",
  "brandade": "brandade",
  "brandy_snaps": "brandy snaps",
  "bratwurst": "bratwurst",
  "bread_pudding": "pudim de pão",
  "bread_soup": "sopa de pão",
  "breakfast_burrito": "burrito",
  "breakfast_sandwich": "sanduíche de café da manhã",
  "breakfast_sausage": "salsicha de café da manhã",
  "brenebon": "brenebon",
  "bridie": "bridie",
  "briouat": "briouat",
  "brisket": "brisket",
  "broa": "broa",
  "brotzeit": "brotzeit",
  "brown_betty": "brown betty",
  "bruckfleisch": "bruck fleisch",
  "brunswick_stew": "brunswick Stew",
  "bruschetta": "bruschetta",
  "bryndzove_halusky": "bryndzové halusky",
  "brændende_kærlighed": "brændende kærlighed",
  "bubble_and_squeak": "bubble and squeak",
  "buchteln": "buchteln",
  "budae_jjigae": "budae jjigae",
  "buddha_jumps_over_the_wall": "buddha jumps over the wall",
  "buddhas_delight": "buddhas delight",
  "buffalo_burger": "hambúrguer de búfalo",
  "buffalo_wing": "buffalo wing",
  "bulgogi": "bulgogi",
  "bull_roast": "bull roast",
  "bun_bo_hue": "bom bo hue",
  "bun_oc": "bom oc",
  "bun_rieu": "bun rieu",
  "bundevara": "abóbora",
  "bundner_nusstorte": "bundner nusstorte",
  "bundt_cake": "bolo de bundt",
  "bungeo_ppang": "bungeo ppang",
  "buntil": "buntil",
  "burgoo": "burgoo",
  "buridda": "buridda",
  "burkinabe_cuisine": "cozinha burquina",
  "burmese_tofu": "tofu birmanês",
  "burnt_ends": "burnt ends",
  "burrito": "burrito",
  "butajiru": "butajiru",
  "butter_chicken": "frango na manteiga",
  "butter_cookie": "biscoito de manteiga",
  "buttermilk_koldskal": "casca fria de leitelho",
  "buttermilk_pie": "torta de leitelho",
  "cabbage_roll": "charuto de repolho",
  "cabbage_soup": "sopa de repolho",
  "cabbie_claw": "cabbie claw",
  "cabidela": "cabidela",
  "cabinet_pudding": "cabinet pudding",
  "cachupa": "cachupa",
  "cactus_fruit": "fruta alcachofra",
  "cacık": "cacık",
  "caesar_salad": "salada césar",
  "cafe_liegeois": "café liégeois",
  "calas": "calas",
  "caldeirada": "caldeirada",
  "caldillo_de_perro": "caldo de cachorro",
  "caldo_de_pollo": "caldo de frango",
  "caldo_de_queso": "caldo de queijo",
  "caldo_de_siete_mares": "caldo dos sete mares",
  "caldo_gallego": "sopa galega",
  "caldo_tlalpeno": "tlalpeno quente",
  "calfs_liver_and_bacon": "fígado de vitela e bacon",
  "california_style_pizza": "pizza estilo califórnia",
  "calisson": "calisson",
  "caltabos": "caltabos",
  "calulu": "calulu",
  "candied_almonds": "amêndoas cristalizadas",
  "canjica": "canjica",
  "cannelloni": "canelone",
  "cannoli": "cannoli",
  "cantaloupe": "melão cantalupo",
  "cantonese_seafood_soup": "sopa de frutos do mar cantonês",
  "caparrones": "caparrones",
  "capirotada": "capirotada",
  "caponata": "caponata",
  "cappon_magro": "cappon magro",
  "caprese_salad": "salada caprese",
  "carac": "carac",
  "carambula": "carambula",
  "caramel": "caramelo",
  "carbonade_flamande": "guisado flamengo",
  "carbonara": "carbonara",
  "carbonnade_flamande": "guisado flamengo",
  "carciofi_alla_giudia": "alcachofras alla giudia",
  "carne_a_la_tampiquena": "carne à tampiquena",
  "carne_asada_fries": "batatas fritas de carne assada",
  "carne_assada": "carne assada",
  "carne_de_porco_a_alentejana": "carne de porco a alentejana",
  "carne_de_vinha_dalhos": "carne de vinha dalhos",
  "carne_pizzaiola": "carne de pizzaiola",
  "carnitas": "carnitas",
  "carrot_cake": "bolo de cenoura",
  "carrozza": "carrozza",
  "cartellate": "cartellate",
  "caruru": "caruru",
  "casatiello": "casatiello",
  "casserole": "caçarola",
  "cassoulet": "cassoulet",
  "castella": "castela",
  "cauliflower": "couve-flor",
  "cawl": "cawl",
  "cecina": "cecina",
  "celery_victor": "celery victor",
  "cemita": "cemita",
  "century_egg": "century egg (ovo preto da china)",
  "cevapi": "cevapi",
  "ceviche": "ceviche",
  "cha_gio": "cha gio",
  "cha_lua": "cha lua",
  "cha_siu_bao": "cha siu bao",
  "chadachadi": "chadachadi",
  "chahan": "chahan",
  "chai_tow_kway": "chai tow kway",
  "chakalaka": "chakalaka",
  "chakapuli": "chakapuli",
  "chakhchoukha": "chakhchoukha",
  "chakodi": "chakodi",
  "chaku": "chaku",
  "challah": "challah",
  "chalupa": "chalupa",
  "champ": "champ",
  "champon": "champon",
  "champorado": "champorado",
  "chana_masala": "chana masala",
  "chanakhi": "chanakhi",
  "chanpuru": "chanpuru",
  "chantilly_cake": "bolo de chantilly",
  "chao_hong_guo": "chao hong guo",
  "chapssal_tteok": "chapssal tteok",
  "char_kway_teow": "char kway teow",
  "char_siu": "char siu",
  "charleston_red_rice": "arroz vermelho charleston",
  "chataamari": "chataamari",
  "chaudin": "chaudin",
  "chawanmushi": "chawanmushi",
  "chazuke": "chazuke",
  "che": "che",
  "cheese_dog": "cheese dog",
  "cheese_dream": "cheese dream",
  "cheese_fries": "fritas com queijo",
  "cheese_plate": "queijo prato",
  "cheese_sandwich": "sanduiche de queijo",
  "cheese_straw": "cheese straw",
  "cheeseburger": "x-burger",
  "cheesecake": "cheesecake",
  "cheesesteak": "cheesesteak",
  "chelsea_bun": "chelsea bun",
  "chermoula": "chermoula",
  "cherries_jubilee": "jubileu de cerejas",
  "cherry": "cereja",
  "cherry_kebab": "kebab de cereja",
  "cherry_pie": "torta de cereja",
  "cherry_rainier": "cherry rainier",
  "cherry_wax_black": "cherry wax black",
  "cherry_wax_red": "cherry wax red",
  "cherry_wax_yellow": "cherry wax yellow",
  "chess_pie": "torta de xadrez",
  "chestnut": "castanha",
  "chhena_gaja": "chhena gaja",
  "chhena_jalebi": "chhena jalebi",
  "chhena_jhili": "chhena jhili",
  "chhena_kheeri": "chhena kheri",
  "chhena_poda": "chhena poda",
  "chicago_style_hot_dog": "cachorro-quente estilo chicago",
  "chicago_style_pizza": "pizza estilo chicago",
  "chicken_a_la_king": "frango a la rei",
  "chicken_and_waffles": "frango e waffles",
  "chicken_bog": "chicken bog",
  "chicken_breast": "peito de frango",
  "chicken_cordon_bleu": "frango cordon bleu",
  "chicken_curry": "curry de galinha",
  "chicken_divan": "chicken divan",
  "chicken_fingers": "chicken fingers",
  "chicken_francaise": "frango francês",
  "chicken_fried_bacon": "chicken fried bacon",
  "chicken_fried_steak": "chicken fried steak",
  "chicken_karahi": "frango karahi",
  "chicken_kiev": "galinha kiev",
  "chicken_marengo": "frango marengo",
  "chicken_maryland": "frango maryland",
  "chicken_nugget": "nugget de frango",
  "chicken_paprikash": "frango paprikash",
  "chicken_provencale": "frango provençal",
  "chicken_quesadilla": "quesadilla de frango",
  "chicken_riggies": "riggies de frango",
  "chicken_sandwich": "sanduíche de frango",
  "chicken_vesuvio": "galinha vesúvio",
  "chicken_wings": "asas de frango",
  "chiffon_cake": "bolo chiffon",
  "chiffon_pie": "torta de chiffon",
  "chikhirtma": "chikhirtma",
  "chikki": "chikki",
  "chilaquiles": "chilaquiles",
  "chile_relleno": "pimentão recheado",
  "chili": "chili",
  "chili_burger": "chili burger",
  "chili_con_carne": "chili com carne",
  "chili_dog": "chili dog",
  "chilli_crab": "chilli crab",
  "chilorio": "chilorio",
  "chim_chum": "chim chum",
  "chimichanga": "chimichanga",
  "chinese_noodles": "macarrão chines",
  "chinese_sausage": "salsicha chinesa",
  "chinese_steamed_eggs": "ovos cozidos chineses",
  "chips_and_dip": "batatas e molho",
  "chireta": "chireta",
  "chislic": "chislic",
  "chistorra": "chistorra",
  "chitranna": "chitranna",
  "choco_pie": "choco pie",
  "chocolate_brownie": "brownie de chocolate",
  "chocolate_cake": "bolo de chocolate",
  "chocolate_chip_cookie": "cookie com gotas de chocolate",
  "chocolate_covered_bacon": "bacon coberto de chocolate",
  "chocolate_covered_potato_chips": "batatas fritas cobertas de chocolate",
  "chocolate_mousse": "mousse de chocolate",
  "chocolate_pudding": "pudim de chocolate",
  "choila": "choila",
  "chole_bhature": "chole bhature",
  "chomchom": "chomchom",
  "chongos_zamoranos": "chongos zamoranos",
  "chop_suey": "chop suey",
  "chorba": "chorba",
  "chorizo": "chouriço",
  "chow_mein": "chow mein",
  "chow_mein_sandwich": "sanduíche de chow mein",
  "chowder": "chowder",
  "chuchvara": "chuchvara",
  "chueo_tang": "chueo tang",
  "churchkhela": "Churchkhela",
  "churma": "churma",
  "churrasco": "churrasco",
  "churros": "churros",
  "chwinamul": "chwinamul",
  "ciabatta_bacon_cheeseburger": "ciabatta bacon cheeseburger",
  "ciauscolo": "ciauscolo",
  "ciccioli": "ciccioli",
  "cifantuan": "cifantuan",
  "cincalok": "cincalok",
  "cincinnati_chili": "cincinnati chili",
  "cinnamon_roll": "rolo de canela",
  "ciorba": "ciorba",
  "ciorba_de_perisoare": "sopa de almôndegas",
  "city_chicken": "city chicken",
  "ciulama": "ciulama",
  "clafoutis": "clafoutis",
  "clam_cake": "bolo de marisco",
  "clam_chowder": "sopa de mariscos",
  "clam_food": "comida de molusco",
  "clams_casino": "cassino de moluscos",
  "claypot_chicken_rice": "claypot chicken rice",
  "clementine": "clementina",
  "clootie": "clootie",
  "club_sandwich": "club sandwich",
  "cobb_salad": "salada cobb",
  "cobbler": "cobbler",
  "coca": "coca",
  "cocada": "cocada",
  "cocada_amarela": "cocada amarela",
  "cochinita_pibil": "cochinita pibil",
  "cocido_lebaniego": "guisado libanês",
  "cocido_madrileno": "cozido madrilenho",
  "cocido_montanes": "cozido montanhês",
  "cockle_bread": "pão de berbigão",
  "cockle_food": "comida de berbigão",
  "coconut_bar": "barra de coco",
  "coconut_cake": "bolo de coco",
  "coconut_rice": "arroz de coco",
  "cocos": "coco",
  "coffee_cake": "bolo de café",
  "colcannon": "colcannon",
  "coleslaw": "salada de repolho",
  "com_tam": "com tam",
  "compote": "compota",
  "coney_island_hot_dog": "cachorro-quente da ilha de coney",
  "confit": "confit",
  "cong_you_bing": "cong you bing",
  "congee": "congee",
  "consomme": "consomê",
  "cookie_salad": "salada de biscoito",
  "coq_au_vin": "coq au vin",
  "coquilles_saint_jacques": "vieiras",
  "cordon_bleu": "cordon bleu",
  "corn": "milho",
  "corn_chowder": "ensopado de milho",
  "corn_cookie": "biscoito de milho",
  "corn_crab_soup": "sopa de milho",
  "corn_dog": "enpanado de salsicha",
  "corn_husk": "casca de milho",
  "corn_pudding": "pudim de milho",
  "corn_relish": "corn relish",
  "cornbread": "pão de milho",
  "cornish_game_hen": "cornish game hen",
  "cornulete": "cornulete",
  "corunda": "corunda",
  "cottage_loaf": "pão de casa",
  "cottage_pie": "torta de cottage",
  "cottage_pudding": "pudim cottage",
  "coulibiac": "coulibiac",
  "couque_de_dinant": "couque de dinant",
  "couscous": "cuscuz",
  "cowboy_beans": "cowboy beans",
  "coyotas": "coyota",
  "cozido_a_portuguesa": "cozido a portuguesa",
  "cozonac": "cozonac",
  "crab_cake": "bolo de caranguejo",
  "crab_food": "comida de caranguejo",
  "crab_louie": "caranguejo louie",
  "cranachan": "cranachan",
  "crappit_heid": "crappit heid",
  "crayfish_food": "comida de lagostim",
  "cream_pie": "torta de creme",
  "creamed_corn": "creme de milho",
  "creamed_eggs_on_toast": "ovos cremosos na torrada",
  "creme_brulee": "creme brulee",
  "creme_caramel": "creme de caramelo",
  "crepe": "crepe",
  "crescentina_modenese": "crescentina modenese",
  "crispy_fried_chicken": "frango frito crocante",
  "cronut": "cronut",
  "croque_madame": "croque madame",
  "croquembouche": "croquembouche",
  "croquette": "croquete",
  "crossing_the_bridge_noodles": "crossing the bridge noodles",
  "cruller": "cruller",
  "crumb_cake": "crumb cake",
  "crumpet": "crumpet",
  "cuban_sandwich": "sanduíche cubano",
  "cuchifritos": "cuchifritos",
  "cucumber_ripe": "pepino maduro",
  "cucumber_soup": "sopa de pepino",
  "cudighi": "cudighi",
  "cullen_skink": "cullen skink",
  "cumian": "cumian",
  "cupcake": "cupcake",
  "curry_bread": "curry bread",
  "curtido": "curtido",
  "custard": "custard",
  "czernina": "czernina",
  "cılbır": "cılbır",
  "dagwood_sandwich": "dagwood sandwich",
  "daheen": "daheen",
  "dahi_vada": "dahi vada",
  "dak_bokkeum_tang": "dak bokkeum tang",
  "dak_galbi": "dak galbi",
  "dakos": "dakos",
  "dal_bhat": "dal bhat",
  "dal_makhani": "dal makhani",
  "dampfnudel": "dampfnudel",
  "dandan_noodles": "macarrão dan dan",
  "dango": "dango",
  "dashi": "dashi",
  "dates": "datte",
  "debrecener": "debrecener",
  "delmonico_steak": "delmonico steak",
  "denver_sandwich": "denver sandwich",
  "derby_pie": "derby pie",
  "dessert_bar": "dessert bar",
  "detroit_style_pizza": "pizza estilo detroit",
  "deviled_crab": "deviled crab",
  "deviled_egg": "ovo cozido",
  "devils_food_cake": "bolo do diabo",
  "dhebra": "dhebra",
  "dhindo": "hindu",
  "dhokla": "dhokla",
  "dhondas": "dhondas",
  "dim_sum": "dim sum",
  "dimlama": "dimlama",
  "diples": "diplos",
  "dirt_cake": "bolo sujo",
  "dirty_macaroni": "dirty macaroni",
  "dirty_rice": "dirty rice",
  "doberge_cake": "doberge cake",
  "dobos_torte": "torta dobos",
  "dobradinha": "dobradinha",
  "dodger_dog": "dodger dog",
  "dodo_ikire": "dodo ikire",
  "doenjang_jjigae": "doenjang jjigae",
  "dolmas": "dolmas",
  "dongan_chicken": "galinha dongan",
  "dongchimi": "dongchimi",
  "donut": "donut",
  "doodhpak": "doodhpak",
  "double_down": "double down",
  "double_ka_meetha": "double ka meetha",
  "doughnut": "rosquinha",
  "douhua": "douhua",
  "douzhi": "douzhi",
  "dovga": "dovga",
  "draw_soup": "draw soup",
  "dressed_herring": "dressed herring",
  "dripping_cake": "drip cake",
  "drunken_noodles": "drunken noodles",
  "duck_blood_and_vermicelli_soup": "sangue de pato e sopa de aletria",
  "duck_rice": "the duck & rice",
  "dulce_de_leche": "doce de leite",
  "dum_aloo": "dum aloo",
  "dumpling": "bolinho de massa",
  "dyrlægens_natmad": "dyrlægens netmad",
  "eba": "eba",
  "eccles_cake": "bolo eccles",
  "eclair": "éclair",
  "edamame": "edamame",
  "efo_riro": "efo riro",
  "egg_drop_soup": "sopa de ovo",
  "egg_roll": "rolinho de ovo",
  "eggplant": "beringela",
  "eggplant_salad": "salada de berinjela",
  "eggs_benedict": "ovos benedict",
  "eggs_neptune": "ovos netuno",
  "eggs_sardou": "eggs sardou",
  "ekuru": "ekuru",
  "elote": "elote",
  "ema_datshi": "ema datshi",
  "empal_gentong": "empal gentong",
  "empanada": "empanada",
  "enchilada": "enchilada",
  "enduri_pitha": "enduri pitha",
  "enne_gai": "enne gai",
  "enormous_omelet_sandwich": "enormous omelet sandwich",
  "entomatada": "entomatada",
  "entrecote": "entrecosto",
  "erbazzone": "erbazzone",
  "erkuai": "erkuai",
  "escalivada": "escalivada",
  "escalope": "costeleta",
  "escargot": "escargot",
  "escudella_i_carn_dolla": "sopa e carne estufada",
  "espetada": "espetada",
  "esterhazy_torte": "torta esterházy",
  "eton_mess": "eton mess",
  "etouffee": "etouffee",
  "eves_pudding": "pudim de véspera",
  "ezogelin_soup": "sopa de mariscos",
  "fabada_asturiana": "feijoada asturiana",
  "fabes_con_almejas": "favas com amêijoas",
  "fahsa": "fahsa",
  "fajita": "fajita",
  "falafel": "falafel",
  "falooda": "falooda",
  "falukorv": "falukorv",
  "farfalle": "farfalle",
  "farikal": "farikal",
  "farl": "farl",
  "fasolada": "fasolada",
  "fasole_cu_carnati": "feijão com salsicha",
  "fatteh": "fatteh",
  "fattoush": "fattoush",
  "feijao_de_oleo_de_palma": "feijao de oleo de palma",
  "feijoada": "feijoada",
  "fesenjan": "fesenjan",
  "fesikh": "fesikh",
  "fettuccine": "fettuccine",
  "fideua": "fideuá",
  "fig": "figo",
  "figgy_pudding": "pudim de figo",
  "filet_mignon": "filet mignon",
  "finger_steaks": "finger steaks",
  "finikia": "finikia",
  "finnan_haddie": "finnan haddie",
  "fios_de_ovos": "fios de ovos",
  "fish_and_chips": "peixe e batatas fritas",
  "fish_ball": "fish ball",
  "fish_head_curry": "curry de cabeça de peixe",
  "fish_slice": "fatia de peixe",
  "fish_stick": "stick de peixe",
  "fishermans_soup": "fisherman's soup",
  "fit_fit": "fit fit",
  "flammekueche": "flammekueche",
  "flan": "flan",
  "flaouna": "flaouna",
  "flaskkorv": "flaskkorv",
  "flaskpannkaka": "flask pannkaka",
  "floating_island": "floating island",
  "florina_pepper": "florina pepper",
  "fluffernutter": "fluffernutter",
  "flummery": "flummery",
  "flying_jacob": "flying jacob",
  "flæskesteg": "flæskesteg",
  "foie_gras": "foie gras",
  "folar": "folar",
  "fondue": "fondue",
  "fools_gold_loaf": "fool's gold loaf",
  "fortune_cookie": "biscoito da sorte",
  "fouee": "fouee",
  "fougasse": "fougasse ",
  "francesinha": "francesinha",
  "francesinha_poveira": "francesinha poveira",
  "frangollo": "frangollo",
  "frejon": "frejon",
  "french_dip": "french dip",
  "french_fries": "batatas fritas",
  "french_onion_soup": "sopa de cebola francesa",
  "french_toast": "torrada francesa",
  "fricasse": "fricassê",
  "frico": "frico",
  "fried_brain_sandwich": "sanduíche de cérebro frito",
  "fried_calamari": "calamari frito",
  "fried_chicken": "frango frito",
  "fried_coke": "coca frita",
  "fried_dough": "massa frita",
  "fried_egg": "ovo frito",
  "fried_eggplant": "berinjela frita",
  "fried_fish": "peixe frito",
  "fried_green_tomatoes": "tomates verdes fritos",
  "fried_ice_cream": "sorvete frito",
  "fried_pie": "torta frita",
  "fried_plantain": "banana frita",
  "fried_rice": "arroz frito",
  "fried_shrimp": "camarão frito",
  "frigarui": "frigarui",
  "frijoles_charros": "charro de feijão",
  "frikadeller": "frikadeller",
  "frikandel": "frikandel",
  "frikkadel": "frikkadel",
  "frittata": "fritada",
  "fritter": "fritter",
  "fritule": "fritule",
  "frogeye_salad": "frog eye salad",
  "frozen_banana": "banana congelada",
  "frozen_yogurt": "iogurte congelado",
  "fruitcake": "bolo de frutas",
  "frybread": "pão frito",
  "fudge": "fudge",
  "fuet": "fuet",
  "fufu": "fufu",
  "fugu_chiri": "fugu chiri",
  "fujian_red_wine_chicken": "fujian red wine chicken",
  "ful_medames": "ful medames",
  "fuling_jiabing": "fuling jiabing",
  "fun_guo": "fun guo",
  "funeral_potatoes": "funeral batatas",
  "funge": "funge",
  "funnel_cake": "bolo de funil",
  "fuqi_feipian": "fuqi feipian",
  "fusi": "fusi",
  "gaat": "gaat",
  "gachas": "gachas",
  "gado_gado": "gado-gado",
  "galaktoboureko": "galaktoboureko",
  "galantine": "galantina",
  "galbi_jjim": "galbi jjim",
  "galbi_tang": "galbi tang",
  "galinha_a_africana": "galinha a africana",
  "galinha_a_portuguesa": "galinha a portuguesa",
  "galinhada": "galinhada",
  "gamja_tang": "gamja tang",
  "garbure": "guarnecer",
  "garden_salad": "garden salad",
  "garganelli": "garganelli",
  "gari": "gari",
  "garlic_bread": "pão de alho",
  "garlic_butter_shrimp": "camarão na manteiga e alho",
  "garmugia": "garmugia",
  "garri": "garry",
  "gazpacho": "gaspacho",
  "gazpachuelo": "gaspachuelo",
  "gbejna": "gbejna",
  "geng": "gangue",
  "gepuk": "gepuk",
  "gerber_sandwich": "gerber sandwich",
  "german_chocolate_cake": "bolo de chocolate alemão",
  "germknodel": "germknodel",
  "ghari": "ghari",
  "gheimeh": "gheimeh",
  "ghevar": "ghevar",
  "ghoriba": "ghoriba",
  "ghormeh_sabzi": "ghormeh sabzi",
  "ghugni": "ghugni",
  "gibassier": "gibassier",
  "gigandes_plaki": "gigandes plaki",
  "gimbap": "gimbap",
  "ginestrata": "ginestrata",
  "ginger_root": "raiz de gengibre",
  "gingerbread": "pão de gengibre",
  "giouvetsi": "giouvetsi",
  "glamorgan_sausage": "salsicha glamorgan",
  "glorified_rice": "glorified rice",
  "gnocchi": "nhoque",
  "gnocco_fritto": "gnocco frito",
  "goetta": "goetta",
  "gofio": "gofio",
  "goi_cuon": "goi cuon",
  "golden_opulence_sundae": "golden opulence sundae",
  "gooey_butter_cake": "gooey butter cake",
  "gopchang_jeongol": "gopchang jeongol",
  "gordita": "gordita",
  "gored_gored": "gored gored",
  "gosh-e_fil": "gosh-e fill",
  "gougere": "gougere",
  "goulash": "goulash",
  "gozinaki": "gozinaki",
  "gołabki": "gołabki",
  "granadilla": "granadilla",
  "grape_blue": "uva roxa",
  "grape_pie": "torta de uva",
  "grape_pink": "uva rosa",
  "grape_white": "uva branca",
  "grapefruit_pink": "toranja rosa",
  "grapefruit_white": "toranja branca",
  "grass_jelly": "getlatina de grama",
  "gratin_dauphinois": "gratin dauphinois",
  "gravlax": "gravlax",
  "greek_salad": "salada grega",
  "green_bean_casserole": "green bean casserole",
  "green_curry": "curry verde",
  "grillades": "grelhado",
  "grilled_cheese_sandwich": "sanduíche de queijo grelhado",
  "grilled_salmon": "salmão grelhado",
  "gringas": "gringas",
  "grits": "grits",
  "guacamole": "guacamole",
  "guaiwei": "guaiwei",
  "guava": "goiaba",
  "gugelhupf": "gugelhupf",
  "guilinggao": "guilinggao",
  "gujeolpan": "gujeolpan",
  "gujia": "gujia",
  "guk": "guk",
  "gulab_jamun": "gulab Jamun",
  "gulai": "gulai",
  "gulyasleves": "gulyasleves",
  "gumbo": "gombo",
  "gundruk": "gundruk",
  "gyeran_jjim": "gyeran jjim",
  "gyeran_ppang": "gyeran ppang",
  "gyoza": "gyoza",
  "gypsy_tart": "tarte cigana",
  "gyro": "gyro",
  "gyudon": "gyudon",
  "gyuhi": "gyuhi",
  "hachee": "hachee",
  "haejang_guk": "haejang guk",
  "haggis": "haggis",
  "hainanese_chicken_rice": "arroz de frango hainanês",
  "hainanese_curry_rice": "arroz com curry hainanês",
  "haleem": "haleem",
  "half_smoke": "half-smoke",
  "halo_halo": "halo-halo",
  "halusky": "halusky",
  "halva": "halva",
  "ham_and_cheese_sandwich": "sanduíche de queijo e presunto",
  "ham_and_eggs": "presunto e ovos",
  "ham_sandwich": "sanduíche de presunto",
  "hamburger": "hamburger",
  "hamdog": "hamdog",
  "hanabiramochi": "hanabiramochi",
  "hangtown_fry": "hangtown fry",
  "happy_faces": "comida rosto feliz",
  "har_cheong_gai": "har cheong gai",
  "har_gow": "har gow",
  "harees": "harees",
  "harihari_nabe": "harihari nabe",
  "harira": "harira",
  "hasty_pudding": "hasty pudding",
  "haupia": "haupia",
  "havregrynskugle": "havregrynskugle",
  "hawaiian_haystack": "palheiro havaiano",
  "hayashi_rice": "arroz hayashi",
  "haystack": "haystack",
  "hazelnut": "hazelnut",
  "higashi": "higashi",
  "himbasha": "himbasha",
  "hinava": "hinava",
  "hiyashi_chuka": "hiyashi chuka",
  "hiyayakko": "hiyayakko",
  "hochzeitssuppe": "hochzeitssuppe",
  "hoe": "hoe",
  "hokkien_fried_rice": "arroz frito hokkien",
  "home_fries": "batatas fritas caseira",
  "honey_cake": "bolo de mel",
  "hong_dou_tang": "hong dou tang",
  "hoppang": "hoppang",
  "hoppin_john": "hoppin' john",
  "hornazo": "hornazo",
  "horseshoe_sandwich": "sanduíche de ferradura",
  "horumonyaki": "horumon yaki",
  "hot_and_sour_soup": "hot & sour soup",
  "hot_brown": "hot brown",
  "hot_chicken": "frango frito picante",
  "hot_dog": "cachorro-quente",
  "hot_dry_noodles": "copo de macarrão quente",
  "hot_milk_cake": "bolo de leite quente",
  "hot_pot": "hot pot",
  "hot_water_corn_bread": "pão de fubá",
  "hot_wiener": "salsicha quente",
  "hotdish": "hotdish",
  "hoto": "hoto",
  "hotteok": "hotteok",
  "huachinango_a_la_veracruzana": "huachinango a la veracruzana",
  "huarache": "huarache",
  "huckleberry": "huckleberry",
  "huevos_divorciados": "huevos divorciados",
  "huevos_motulenos": "huevos motulenos",
  "huevos_rancheros": "huevos rancheros",
  "huitre": "ostra gratinada",
  "hulatang": "hulatang",
  "hummingbird_cake": "hummingbird cake",
  "hummus": "húmus",
  "hushpuppy": "hushpuppy",
  "hyderabadi_biryani": "hyderabadi biryani",
  "ice_cream": "sorvete",
  "ice_cream_cake": "bolo de sorvete",
  "icebox_cake": "icebox cake",
  "iced_bun": "bun gelado",
  "idiyappam": "idiyappam",
  "idli": "idli",
  "ikan_goreng": "ikan goreng",
  "imagawayaki": "imagawayaki",
  "imarti": "imarti",
  "imoni": "imoni",
  "injera": "injera",
  "instant_boiled_mutton": "instant-boiled mutton",
  "isterband": "isterband",
  "italian_beef": "carne italiana",
  "italian_hot_dog": "cachorro-quente italiano",
  "jalebi": "jalebi",
  "jam_roly_poly": "jam roly-poly",
  "jambalaya": "jambalaya",
  "jambon_persille": "jambon persille",
  "jamon": "jamón",
  "jamon_iberico": "jamón ibérico",
  "jamon_serrano": "jamón serrano",
  "janchi_guksu": "janchi guksu",
  "janssons_frestelse": "janssons frestelse",
  "japanese_curry": "curry japonês",
  "japchae": "japchae",
  "jello_salad": "salada de gelatina",
  "jelly_bean": "jujuba",
  "jeongol": "jeongol",
  "jeow_bong": "jeow bong",
  "jerky": "jerky",
  "jhunka": "jhunka",
  "jian_dui": "jian dui",
  "jianbing": "jianbing",
  "jiaozi": "jiaozi",
  "jibarito": "jibarito",
  "jing_jiang_rou_si": "jing jiang rou si",
  "jingisukan": "jingisukan",
  "jiuniang": "jiuniang",
  "jjigae": "jjigae",
  "johnny_marzetti": "johnny marzetti",
  "johnnycake": "johnnycake",
  "jokai_bean_soup": "jokai bean soup",
  "jokbal": "jokbal",
  "jolada_rotti": "jolada rotti",
  "jollof_rice": "arroz jollof",
  "jolpan": "jolpan",
  "jook_sing_noodles": "massa de jook-sinj",
  "jucy_lucy": "juicy lucy",
  "jujeh_kabab": "jujeh kabab",
  "kaak": "kaak",
  "kaassouffle": "kaassouffle",
  "kabob": "kabob",
  "kabuni": "kabuni",
  "kacamak": "kačamak",
  "kachori": "kachori",
  "kachumbari": "kachumbari",
  "kadhi": "kadhi",
  "kaeng_khae": "kaeng khae",
  "kaeng_pa": "kaeng pa",
  "kaeng_som": "kaeng som",
  "kaeng_tai_pla": "kaeng tai pla",
  "kai_yang": "kai yang",
  "kaipen": "kaipen",
  "kaju_katli": "kaju katli",
  "kakara_pitha": "kakara pitha",
  "kaki": "kaki",
  "kakigori": "kakigori",
  "kakuni": "kakuni",
  "kal_guksu": "kalguksu",
  "kalach": "kalach",
  "kalakand": "kalakand",
  "kalakukko": "kalakukko",
  "kalamay": "kalamay",
  "kaldereta": "kaldereta",
  "kalduny": "kalduny",
  "kalu_dodol": "kalu dodol",
  "kamameshi": "kamameshi",
  "kanafeh": "kanafeh",
  "kansar": "kansar",
  "karasumi": "karasumi",
  "karađorđeva_snicla": "karađorđeva šnicla",
  "kare_kare": "karê",
  "karelian_pasty": "karelian pasty",
  "karnıyarık": "umbigo",
  "kartoffelkase": "kartoffelkase",
  "karydopita": "karydopita",
  "kateh": "kateh",
  "katsudon": "katsudon",
  "kaya_toast": "kaya toast",
  "kedgeree": "kedgeree",
  "kedjenou": "kedjenou",
  "keledos": "keledos",
  "kenkey": "kenkey",
  "kentucky_jam_cake": "bolo de geléia do kentucky",
  "kerak_telor": "kerak telor",
  "keskek": "keskek",
  "kesme": "kesme",
  "ketoprak": "ketoprak",
  "ketupat": "ketupat",
  "key_lime_pie": "key lime pie",
  "khabees": "khabees",
  "khachapuri": "khachapuri",
  "khai_yat_sai": "khai yat sai",
  "khaja": "khaja",
  "khakhra": "khakhra",
  "khanom_chan": "khanom chan",
  "khanom_mo_kaeng": "khanom mo kaeng",
  "khanom_tan": "khanom tan",
  "khao_soi": "khao soi",
  "kharcho": "kharcho",
  "khash": "khash",
  "khatkhate": "khatkhate",
  "khauk_swe_thoke": "khauk swe thoke",
  "kheer": "kheer",
  "khichdi": "khichdi",
  "khichu": "khichu",
  "khinkali": "khinkali",
  "khira_sagara": "khira sagara",
  "khubz": "khubz",
  "kibbeh": "quibe",
  "kibinai": "kibinai",
  "kielbasa": "kielbasa",
  "kifli": "kifli",
  "kig_ha_farz": "kig ha farz",
  "kilishi": "kilishi",
  "kimchi": "kimchi",
  "kimchi_buchimgae": "kimchi buchimgae",
  "kimchi_fried_rice": "kimchi arroz frito",
  "kimchi_jjigae": "kimchi jjigae",
  "kinema": "kinema",
  "king_cake": "bolo rei",
  "kipper": "kipper",
  "kiritanpo": "kiritanpo",
  "kisra": "kisra",
  "kissel": "kissel",
  "kitcha": "kitcha",
  "kitfo": "kitfo",
  "kiwi": "quiuí",
  "kladdkaka": "kladdkaka",
  "knedle": "knedle",
  "knickerbocker_glory": "knickerbocker glory",
  "knish": "knish",
  "knodel": "knödel",
  "koba": "koba",
  "kofta": "kofta",
  "kohlrabi": "couve-rábano",
  "koi": "koi",
  "kokis": "kokis",
  "kokonte": "kokonte",
  "kokoretsi": "kokoretsi",
  "kolach": "kolache",
  "kolokythopita": "kolokythopita",
  "kombdi_vade": "kombdi vade",
  "kompot": "kompot",
  "kondowole": "kondowole",
  "konkonte": "konkonte",
  "konro": "konro",
  "koozh": "koozh",
  "kopytka": "kopytka",
  "korokke": "korokke",
  "korovai": "korovai",
  "kosambari": "kosambari",
  "kotlet_schabowy": "kotlet schabowy",
  "kottbullar": "köttbullar",
  "kottu": "kottu",
  "kouign_amann": "kouign-amann",
  "koulourakia": "koulourakia",
  "kozhukkatta": "kozhukkatta",
  "kralan": "kralan",
  "kringle": "kringle",
  "krofne": "krofne",
  "kroppkaka": "kroppkaka",
  "krostule": "krostule",
  "krowki": "krowki",
  "krumkake": "krumkake",
  "kuchmachi": "kuchmachi",
  "kuciukai": "kuciukai",
  "kuih": "kuih",
  "kulfi": "kulfi",
  "kuli_kuli": "kuli kuli",
  "kulich": "kulich",
  "kulolo": "kulolo",
  "kuluban": "kuluban",
  "kumquats": "kumquat",
  "kung_pao_chicken": "frango kung pao",
  "kurtoskalacs": "kurtos kalacs",
  "kushari": "koshary",
  "kushikatsu": "kushikatsu",
  "kutia": "kutiá",
  "kutsinta": "kutsinta",
  "kuurdak": "kuurdak",
  "kwarezimal": "kwareżima",
  "lablabi": "lablabi",
  "ladob": "ladob",
  "lady_baltimore_cake": "lady baltimore cake",
  "lahoh": "lahoh",
  "lai_fun": "lai fun",
  "lakhamari": "lakhamari",
  "lalab": "lalab",
  "lamian": "lamian",
  "landjager": "landjäger",
  "lane_cake": "lane cake",
  "langos": "lángos",
  "laobing": "laobing",
  "lapa": "lapa",
  "laping": "lapping",
  "lapskaus": "labskaus",
  "larb": "larb",
  "lasagna": "lasanha",
  "laulau": "lau-lau",
  "laverbread": "laver bread",
  "lawar": "lawar",
  "lazarakia": "lazarakia",
  "laziji": "laziji",
  "lebanon_bologna": "lebanon bologna",
  "leberkase": "leberkäse",
  "leberknodel": "leberknodel",
  "lechazo": "lechazo",
  "lecso": "lecso",
  "leek_soup": "leek soup",
  "lekor": "lekor",
  "lemang": "lemang",
  "lemon": "limão",
  "lemon_ice_box_pie": "lemon ice box pie",
  "lemon_meyer": "limão meyer",
  "lettuce_soup": "sopa de alface",
  "liangfen": "liangfen",
  "liangpi": "liangpi",
  "limburger_sandwich": "limburger sandwich",
  "limes": "lima",
  "limpet_food": "lapa",
  "linguine": "linguine",
  "linzer_torte": "linzer torte",
  "litti": "litti",
  "liver_and_onions": "fígado acebolado",
  "liver_pate": "patê de fígado",
  "liver_soup": "sopa de fígado",
  "lo_mai_chi": "lo mai chi",
  "lo_mai_gai": "lo mai gai",
  "lo_mein": "lo mein",
  "lobiani": "lobiani",
  "lobio": "lóbio",
  "lobster_bisque": "sopa de lagosta",
  "lobster_food": "comida de lagosta",
  "lobster_newberg": "lagosta newberg",
  "lobster_roll": "cachorro-quente de lagosta",
  "lobster_roll_sandwich": "sanduíche de lagosta",
  "lobster_stew": "ensopado de lagosta",
  "lobster_thermidor": "termidor de lagosta ",
  "loco_moco": "muco louco",
  "lokma": "lokma",
  "london_broil": "londres broil",
  "london_bun": "london bun",
  "lontong": "lontong",
  "lontong_cap_go_meh": "lontong cap go meh",
  "loukaniko": "loukaniko",
  "luchi": "luchi",
  "lunch": "lunch",
  "lung_fung_soup": "lung fung soup",
  "lutefisk": "lutefisk",
  "luther_burger": "luther burger",
  "lychee": "lichia",
  "maafe": "mafê",
  "maamoul": "maamoul",
  "macaron": "macaron",
  "macaroni_and_cheese": "macarrão com queijo",
  "macaroni_salad": "salada de macarrão",
  "macaroni_soup": "sopa de macarrão",
  "maccu": "maccu",
  "machaca": "machaca",
  "machher_jhol": "machher jhol",
  "madeleine": "madeleine",
  "maeun_tang": "maeun-tang",
  "magenbrot": "magenbrot",
  "magiritsa": "magiritsa",
  "majboos": "majboos",
  "majjige_huli": "majjige huli",
  "mak_guksu": "mak guksu",
  "makchang": "makchang",
  "makdous": "makdous",
  "makowiec": "makowiec",
  "makroudh": "makroudh",
  "mala_mogodu": "mala mogodu",
  "malloreddus": "malloreddus",
  "malpua": "malpua",
  "malva_pudding": "malva pudding",
  "malvern_pudding": "malvern pudding",
  "mamaliga": "mamaliga",
  "mammi": "mammi",
  "manakish": "manakish",
  "manchet": "manchet",
  "mandarine": "mandarina",
  "mandi": "mandi",
  "mandu_guk": "mandu guk",
  "manestra": "minestra",
  "mango": "manga",
  "mango_pudding": "pudim de manga",
  "mango_red": "manga vermelha",
  "mango_sticky_rice": "arroz de manga",
  "mangostan": "mangostão",
  "manicotti": "manicotti",
  "manju": "manju",
  "manti": "manti",
  "mantou": "mantou",
  "maple_bacon_donut": "bonuts de bacon",
  "mapo_doufu": "mapo doufu",
  "maqluba": "maqluba",
  "maraca_pie": "maraca pie",
  "maracuja": "maracujá",
  "marble_cake": "marble cake",
  "marie_biscuit": "biscoito maria",
  "marry_girl_cake": "bolo de casamento",
  "mas_riha": "mas riha",
  "masgouf": "masgouf",
  "mashed_potato": "purê de batata",
  "mashed_pumpkin": "purê de abóbora",
  "massaman_curry": "caril massaman",
  "matbukha": "matbukha",
  "matelote": "matelote",
  "mattentaart": "mattentaart",
  "matzo_ball": "bolinha de matze",
  "maultasche": "maultaschen",
  "maxwell_street_polish": "maxwell street polish",
  "mazurek": "mazurek",
  "mealie_bread": "mealie bread",
  "meat_from_tiblica": "carne de tiblica",
  "meatball": "almôndega",
  "meatcake": "bolo de carne",
  "meatloaf": "rolo de carne",
  "mechoui": "méchoui",
  "medisterpølse": "medisterpølse",
  "mee_pok": "mee pok",
  "mee_siam": "mee siam",
  "meeshay": "meeshay",
  "mekitsa": "mekitsa",
  "melomakarono": "melomakarano",
  "melon_piel_de_sapo": "melon piel de sapo",
  "melonpan": "melonpan",
  "melt_sandwich": "melt sandwich",
  "memela": "memela",
  "menemen": "menemen",
  "menudo": "menudo",
  "merguez": "merguez",
  "meringue": "merengue",
  "meze": "meze",
  "međimurska_gibanica": "međimurska gibanica",
  "mi_krop": "krop mi",
  "miang_kham": "miang kham",
  "michigan_hot_dog": "cachorro-quente michigan",
  "michigan_salad": "salada michigan",
  "mie_kangkung": "mie kangkung",
  "mie_kocok": "mie kocok",
  "milho_frito": "milho frito",
  "milk_toast": "torrada de leite",
  "mille_feuille": "mil-folhas",
  "millionbøf": "millionbøf",
  "mince_and_tatties": "mince and tatties",
  "mince_pie": "tortinha britânica",
  "minchee": "minchi",
  "minestra_di_ceci": "sopa de grão de bico",
  "minestrone": "minestrone",
  "misal": "misal",
  "miso_soup": "sopa de missô",
  "mission_burrito": "burrito",
  "mississippi_mud_pie": "mississippi mud pie",
  "misua": "misua",
  "mititei": "mititei",
  "mitraillette": "mitraillette",
  "mixian": "mixian",
  "mixiote": "mixiote",
  "miyan_kuka": "miyan kuka",
  "miyeok_guk": "miyeok guk",
  "mlinci": "mlinci",
  "moambe": "moamba",
  "mochi": "mochi",
  "modak": "modak",
  "modjeska": "modjeska",
  "moin_moin": "moin-moin",
  "mollete": "mollete",
  "molote": "molote",
  "mont_di": "mont di",
  "monte_cristo_sandwich": "sanduíche monte cristo",
  "moo_goo_gai_pan": "moo goo gai pan",
  "moo_shu_pork": "moo shu pork",
  "mooncake": "mooncake",
  "moravian_spice_cookies": "biscoitos morávio",
  "moronga": "moronga",
  "mortadella": "mortadela",
  "mostaccioli": "mostaccioli",
  "mostarda": "mostarda",
  "mother_in_law": "mother in law",
  "motsunabe": "motsunabe",
  "moules_frites": "mexilhões fritos",
  "moussaka": "moussaka",
  "moustalevria": "mustalevria",
  "mozzarella_sticks": "palitos de mussarela",
  "mrouzia": "mrouzia",
  "mu_kratha": "mu kratha",
  "muamba_chicken": "moamba de galinha",
  "mucenici": "mucenici",
  "muckalica": "muckalica",
  "mucver": "mücver",
  "muesli": "muesli",
  "muffuletta": "muffuleta",
  "mughlai_paratha": "paratha de mughlai ",
  "muhallebi": "muhallebi",
  "mulberry": "amora",
  "mulligan_stew": "guisado de mulligan",
  "mulukhiyah": "mulukhiyah",
  "muraturi": "muraturi",
  "murgh_musallam": "murgh musallam",
  "murtabak": "murtabak",
  "musakhan": "musakhan",
  "mussel": "mexilhão",
  "mustacciuoli": "mustacciuoli",
  "mustamakkara": "mustamakkara",
  "mutton_curry": "mutton curry",
  "mykyrokka": "mykyrokka",
  "mysore_pak": "mysore pak",
  "nabak_kimchi": "nabak kimchi",
  "nacho": "nacho",
  "naem": "naem",
  "naengmyeon": "naengmyeon",
  "nam_khao": "nam khao",
  "nam_ngiao": "nam ngiao",
  "nam_tok": "nam tok",
  "namagashi": "namagashi",
  "namasu": "namasu",
  "namul": "namul",
  "nan_gyi_thohk": "nan gyi thohk",
  "nanbanzuke": "nanbanzuke",
  "naryn": "naryn",
  "nasi_bogana": "nasi bogana",
  "nasi_campur": "nasi campur",
  "nasi_dagang": "nasi dagang",
  "nasi_lemak": "nasi lemak",
  "nasi_liwet": "nasi liwet",
  "nasi_timbel": "nasi timbel",
  "nasi_tumpang": "nasi tumpang",
  "natchitoches_meat_pie": "natchitoches meat pie",
  "natto": "natto",
  "ndole": "ndolé",
  "neapolitan_pizza": "pizza napolitana",
  "nectarine": "nectarina",
  "nectarine_flat": "nectarina plana",
  "new_england_boiled_dinner": "new england boiled dinner",
  "new_haven_style_pizza": "pizza estilo new haven",
  "new_york_style_pizza": "pizza estilo nova york",
  "ngo_hiang": "ngo hiang",
  "nian_gao": "nian gao",
  "nihari": "nihari",
  "nikujaga": "nikujaga",
  "nikuman": "nikuman",
  "nimono": "nimono",
  "nopalito": "nopal",
  "noppe": "noppe",
  "nshimansima": "nshimasima",
  "nuea_phat_phrik": "nuea phat phrik",
  "nut_forest": "nut forest",
  "nut_pecan": "noz-pecã",
  "nut_roll": "rolo de nozes",
  "obatzda": "obatzda",
  "obi_non": "obi non",
  "octopus": "polvo",
  "oden": "oden",
  "oeufs_en_meurette": "ovos meurette",
  "ogbono_soup": "sopa de ogbono",
  "ogi": "ogi",
  "ogok_bap": "ogok-bap",
  "ohaw": "ohaw",
  "ohn_no_khao_swe": "ohn no khao swè",
  "oil_noodles": "macarrão ao óleo",
  "okinawa_soba": "okinawa soba",
  "okonomiyaki": "okonomiyaki",
  "okroshka": "okroshka",
  "oliebol": "oliebol",
  "olla_podrida": "olla podrida",
  "ollada": "ollada",
  "omelette": "omelete",
  "omo_tuo": "omo tuo",
  "omurice": "omurice",
  "onigiri": "onigiri",
  "onion_red": "cebola vermelha",
  "onion_red_peeled": "cebola roxa",
  "onion_ring": "anel de cebola",
  "onion_white": "cebola branca",
  "orange": "laranja",
  "orange_chicken": "frango com molho de laranja",
  "orange_cuttlefish": "lula",
  "ori_tang": "ori tang",
  "orzo": "orzo",
  "osechi": "osechi",
  "osso_buco": "ossobuco",
  "ostkaka": "ostkaka",
  "ostropel": "ostropel",
  "ox_tongue_pastry": "ox-tongue pastry",
  "oxtail_soup": "Sopa de rabada",
  "oxtail_stew": "guisado de rabo de boi",
  "oyakodon": "oyakodon",
  "oyster": "ostra",
  "oyster_bienville": "ostra bienville",
  "oyster_en_brochette": "ostra no espeto",
  "oyster_omelette": "omelete de ostra",
  "oyster_rockefeller": "ostra rockefeller",
  "pa_amb_tomaquet": "pão com tomate",
  "pachi_pulusu": "pachi pulusu",
  "paczki": "Pączki",
  "pad_thai": "pad thai",
  "paella": "paella",
  "pain_au_chocolat": "pain au chocolat",
  "pajeon": "pajeon",
  "pakhala": "pakhala",
  "pakora": "pakora",
  "palak_paneer": "palak paneer",
  "palatschinke": "palatschinke",
  "paling_in_t_groen": "paling in ‘t groen",
  "palitaw": "palitaw",
  "paloc_soup": "palóc soup ",
  "pambazo": "pambazo",
  "pampushka": "pampushka",
  "pan_bagnat": "pan bagnat",
  "pan_de_muerto": "pan de muerto",
  "pan_dulce": "pão doce",
  "panada": "panada",
  "pancake": "panqueca",
  "pane_carasau": "pão carasau",
  "pane_di_altamura": "pão de altamura",
  "paneer_tikka": "paneer tikka",
  "panelle": "panelle",
  "panellets": "panellet",
  "panettone": "panettone",
  "panjiri": "panjiri",
  "panna_cotta": "panna cotta",
  "pannenkoek": "pannenkoek",
  "panocha": "panocha",
  "pansotti": "pansotti",
  "pantua": "pantuá",
  "panucho": "panucho",
  "pao_cai": "pao cai",
  "pap": "papa",
  "papaya": "mamão",
  "papet_vaudois": "papet vaudois",
  "pappa_al_pomodoro": "pappa al pomodoro",
  "parfait": "parfait",
  "parker_house_roll": "parker house roll",
  "parmigiana": "parmesão",
  "pasanda": "pasanda",
  "paska": "paska",
  "paskha": "paskha",
  "passatelli": "passatelli",
  "passion_fruit": "maracujá",
  "pasta_salad": "salada de macarrão",
  "pastel_azteca": "bolo asteca",
  "pastel_de_nata": "bolo de nata",
  "pastiera": "pastiera",
  "pastilla": "pastilla",
  "pastitsio": "pastitsio",
  "pastrami_on_rye": "pastrami de centeio",
  "pastry": "pastry",
  "pastry_heart": "pastry heart",
  "pasulj": "pasulj",
  "patatnik": "patatnik",
  "pate": "patê",
  "pate_aux_pommes_de_terre": "pate aux pommes de terre",
  "pathiri": "pathiri",
  "patoleo": "patoleo",
  "patty": "patty",
  "patty_melt": "patty melt",
  "pavlova": "pavlova",
  "pea_soup": "sopa de ervilha",
  "peach": "pêssego",
  "peach_flat": "pêssego plana",
  "peach_melba": "pêssego melba",
  "peanut_butter": "manteiga de amendoim",
  "peanut_butter_and_jelly_sandwich": "sanduíche de manteiga de amendoim e geleia",
  "peanut_butter_cookie": "biscoito de manteiga de amendoim",
  "peanut_soup": "sopa de amendoim",
  "pear": "pera",
  "pear_abate": "pera abate",
  "pear_forelle": "pera forelle",
  "pear_kaiser": "pera kaiser",
  "pear_monster": "pera monstro",
  "pear_red": "pera vermelha",
  "pear_stone": "pera stone",
  "pear_williams": "pera williams",
  "pecan_pie": "torta de nozes",
  "pecel_lele": "pecel lele",
  "peking_duck": "pato de pequim",
  "pemmican": "pemmican",
  "penne": "macarrão penne",
  "pepino": "pepino",
  "pepper_green": "pimenta verde",
  "pepper_orange": "pimenta laranja",
  "pepper_red": "pimenta vermelha",
  "pepper_steak": "bife com pimenta",
  "pepper_yellow": "pimenta amarela",
  "pepperoni": "calabresa",
  "pepperoni_roll": "rolinho de calabresa",
  "peppersoup": "sopa de pimenta",
  "persimmon_pudding": "pudim de caqui",
  "petit_gateau": "petit gâteau",
  "phanaeng_curry": "panang curry",
  "phat_khing": "phat khing",
  "phat_phrik_khing": "phat phrik khing",
  "phat_si_io": "phat si-io",
  "philippine_adobo": "adobo filipino",
  "pho": "pho",
  "physalis": "physalis",
  "physalis_with_husk": "physalis com casca",
  "piadina": "piadina",
  "picadillo": "picadillo",
  "pichelsteiner": "pichelsteiner",
  "pickled_cucumber": "pepino em conserva",
  "pico_de_gallo": "pico de galo",
  "pie_a_la_mode": "torta a la mode",
  "pie_tee": "pie tee",
  "pieds_paquets": "pieds paquets",
  "pierogi": "pierogi",
  "pigs_in_a_blanket": "pigs in a blanket",
  "pihtije": "pihtije",
  "pilaf": "Arroz pilaf",
  "pincho": "pincho",
  "pineapple": "abacaxi",
  "pineapple_mini": "mini abacaxi",
  "pinnekjøtt": "pinnekjøtt",
  "piperade": "piperade",
  "pirao": "pirão",
  "pirog": "pirog",
  "pirozhki": "pirozhki",
  "pisarei_e_faso": "pisarei e faso",
  "pissaladiere": "pissaladière",
  "pistachio_pudding": "pudim de pistache",
  "pisto": "pisto",
  "pistolette": "pistolette",
  "pitahaya_red": "pitaya",
  "pitha": "pitha",
  "piti": "piti",
  "pitsi_pitsi": "pitsi pitsi",
  "pizokel": "pizokel",
  "pizza": "pizza",
  "pizza_bagel": "pizza de bagel",
  "pizzoccheri": "pizzoccheri",
  "pkhali": "pkhali",
  "placinta": "placinta",
  "pljeskavica": "pljeskavica",
  "ploye": "ploye",
  "plum": "ameixa",
  "po_boy": "po boy",
  "poached_egg": "ovo poché",
  "poc_chuc": "poc chuc",
  "podvarak": "podvarak",
  "poffertjes": "poffertjes",
  "pogaca": "pogaca",
  "poi": "poi",
  "poke": "poke",
  "polenta": "polenta",
  "polkagris": "polkagris",
  "pollock_roe": "ovas de pollock",
  "polsa": "polsa",
  "pomegranate": "romã",
  "pomelo_sweetie": "doce de pomelo",
  "ponganalu": "ponganalu",
  "poornalu": "poornalu",
  "pootharekulu": "pootharekulu",
  "popara": "popara",
  "popiah": "popiah",
  "popover": "popovers",
  "poppyseed_muffin": "muffin de papoula",
  "pork_and_beans": "carne de porco e feijão",
  "pork_blood_soup": "sopa de sangue de porco",
  "pork_bones": "ossos de porco",
  "pork_chop": "costelinha de porco",
  "pork_jelly": "geleia de porco",
  "pork_roll": "rolinho de porco",
  "pork_tenderloin_sandwich": "sanduíche de lombo de porco",
  "porra_antequerana": "porra antequerana",
  "porridge": "porridge",
  "portuguese_seafood_rice": "arroz de marisco português",
  "potato_red": "batata vermelha",
  "potato_red_washed": "batata vermelha lavada",
  "potato_salad": "salada de batata",
  "potato_skins": "casca de batata",
  "potato_sweet": "batata doce",
  "potato_wedges": "batatas gomos",
  "potato_white": "batata branca",
  "potatoes_obrien": "batatas obrien",
  "potbrood": "potbrood",
  "potee": "potee",
  "potpie": "pot pie",
  "pound_cake": "pound cake",
  "poutine": "poutine",
  "pozharsky_cutlet": "costeleta pozharsky",
  "pozole": "pozole",
  "prawn_ball": "bolinho de camarão",
  "press_cake": "press cake",
  "prime_rib": "prime rib",
  "princess_cake": "princess cake",
  "pringa": "pringa",
  "prinskorv": "prinskorv",
  "profiterole": "profiterole",
  "prosciutto": "prosciutto",
  "prosciutto_di_norcia": "prosciutto di norcia",
  "protein_bar": "Barra de proteínas",
  "psarosoupa": "psarosoupa",
  "puff_puff": "puff-puff",
  "puliyogare": "puliyogare",
  "pulled_pork_sandwich": "sanduíche de porco desfiado",
  "pumpkin_coconut_custard": "pudim de abóbora",
  "pumpkin_pie": "torta de abóbora",
  "punjena_paprika": "pimentão recheado",
  "punsch_roll": "punsch roll",
  "punugulu": "punugulu",
  "puran_poli": "puran poli",
  "puri": "poori",
  "pustakari": "pustakari",
  "puto": "puto",
  "puttu": "puttu",
  "pyttipanna": "pyttipanna",
  "qatayef": "qatayef",
  "qazı": "qazı",
  "qeema": "keema",
  "quad_city_style_pizza": "pizza estilo quad city",
  "quarkkaulchen": "quarkkeulchen",
  "qubani_ka_meetha": "qubani-ka-meetha",
  "queijo_do_pico": "queijo do pico",
  "quenelle": "quenelle",
  "quesadilla": "quesadilla",
  "queso_flameado": "queijo flambado",
  "quiche": "quiche",
  "quince": "marmelo",
  "qutab": "qutab",
  "quzi": "quzi",
  "rab_cake": "rab cake",
  "rabbit_pie": "torta de coelho",
  "rabri": "rabri",
  "raclette": "raclette",
  "racuchy": "racuchy",
  "ragi_mudde": "ragi mudde",
  "ragout": "ragu",
  "raita": "raita",
  "rajas_con_crema": "rajas con crema",
  "rajma": "rajma",
  "rakfisk": "rakfisk",
  "rambutan": "rambutan",
  "ramen": "ramen",
  "ras_malai": "rasmalai",
  "rasgulla": "rasgulla",
  "raspberry": "framboesa",
  "rassolnik": "rassolnik",
  "rat_na": "rat na",
  "ratatouille": "ratatouille",
  "ravioli": "ravioli",
  "red_beans_and_rice": "feijão vermelho e arroz",
  "red_braised_pork_belly": "barriga de porco assada vermelha",
  "red_curry": "curry vermelho",
  "red_velvet_cake": "bolo red velvet",
  "redcurrant": "groselha",
  "rendang": "rendang",
  "reuben": "reuben",
  "reuben_sandwich": "reuben sandwich",
  "revithia": "revithia",
  "rhubarb_pie": "rhubarb pie",
  "ribollita": "ribollita",
  "rice": "arroz",
  "rice_and_gravy": "arroz e molho",
  "rice_krispies_treats": "krispies de arroz",
  "rice_pudding": "arroz doce",
  "rigatoni": "rigatoni",
  "rigo_jancsi": "rigo jancsi",
  "rijstevlaai": "rijstevlaai",
  "rinflajs": "rinflajs",
  "risalamande": "risalamande",
  "riso_patate_e_cozze": "riso patate e cozze",
  "risotto": "risoto",
  "rissole": "risole",
  "roast_beef": "carne assada",
  "roast_beef_sandwich": "sanduíche de carne assada",
  "roccoco": "rococó",
  "rock_cake": "rock cake",
  "rogan_josh": "rogan josh",
  "rolled_oyster": "rolled oyster",
  "rollmops": "rollmops",
  "romeritos": "romeritos",
  "ronttonen": "ronttonen",
  "ropa_vieja": "ropa vieja",
  "rosca_de_reyes": "rosca de reyes",
  "rose_hip_soup": "rose hip soup",
  "rossypottu": "rössypottu",
  "rostbratel": "rostbraten",
  "rosti": "rosti",
  "roti_jala": "roti jala",
  "roulade": "roulade",
  "rozata": "rozata",
  "rugulah": "rugulah",
  "rullepølse": "rullepølse",
  "rum_baba": "baba ao rum",
  "runeberg_torte": "torta runeberg",
  "runza": "runza",
  "rusk": "rusk",
  "ruske_kape": "bolo de coco caseiro com chocolate",
  "russian_tea_cake": "bolo de chá russo",
  "rye_bread": "pão de centeio",
  "rødgrød": "rødgrød",
  "sabaayad": "sabaayad",
  "sabich_salad": "salada de sabic",
  "sabudana_khichadi": "sabudana khichri",
  "sachertorte": "sachertorte",
  "sachima": "sachima",
  "sadhya": "sadhya",
  "saffron_bun": "pão de açafrão",
  "sago": "sagu",
  "sago_soup": "sopa de sagu",
  "sai_ua": "sai ua",
  "sailor_sandwich": "sailor sandwich",
  "sakotis": "sakotis",
  "salad": "salada",
  "salade_nicoise": "salada niçoise",
  "salak": "salak",
  "salami": "salame",
  "salata_de_boeuf": "salata de boeuf",
  "salbute": "salbute",
  "saleeg": "saleeg",
  "salisbury_steak": "salisbury steak",
  "salmorejo": "salmorejo",
  "salo": "salo",
  "salt_potatoes": "salt potatoes",
  "salt_water_taffy": "salt water taffy",
  "saltah": "saltah",
  "saltimbocca": "saltimbocca",
  "salty_liquorice": "salty liquorice",
  "samay_baji": "samay baji",
  "sambal_stingray": "sambal stingray",
  "sambar": "sambar",
  "samgye_tang": "samgyetang",
  "samosa": "samosa",
  "san_nakji": "sannakji",
  "sandesh": "sandesh",
  "sandwich": "sanduíche",
  "sandwich_loaf": "sandwich loaf",
  "sanna": "sanna",
  "santula": "santula",
  "sapin_sapin": "sapin sapin",
  "sarapatel": "sarapatel",
  "sarburma": "sarburma",
  "sardenara": "sardenara",
  "sarma": "sarma",
  "sarson_da_saag": "sarson ka saag",
  "sartu": "sartu",
  "sashimi": "sashimi",
  "sataras": "sataras",
  "satay": "satay",
  "satsivi": "satsivi",
  "sauerbraten": "sauerbraten",
  "sauerkraut": "chucrute",
  "sausage": "salsicha",
  "sausage_gravy": "molho de salsicha",
  "sausage_roll": "rolo de salsicha",
  "sausage_sandwich": "sanduíche de salsicha",
  "sausage_stroganoff": "strogonoff de salsicha",
  "sauteed_reindeer": "sautéed reindeer",
  "savarin": "savarin",
  "sayur_asem": "sayur asem",
  "sayur_lodeh": "sayur lodeh",
  "scallop": "vieira",
  "scampi": "scampi",
  "schiacciata": "schiacciata",
  "schnitzel": "schnitzel",
  "schupfnudel": "schupfnudeln",
  "schuxen": "schuxen",
  "schweinshaxe": "schweinshaxe",
  "sciusceddu": "sciusceddu",
  "scotch_broth": "caldo escocês",
  "scotch_egg": "ovo escocês",
  "scotch_pie": "torta escocesa",
  "scotcheroos": "scotcheroos",
  "scrambled_eggs": "ovos mexidos",
  "scrapple": "rocambole de carne",
  "sea_cucumber": "pepino do mar",
  "seafood_birdsnest": "seafood birdsnest",
  "sealed_crustless_sandwich": "sanduíche sem crosta selado",
  "seattle_style_hot_dog": "cachorro-quente estilo seattle",
  "seaweed_salad": "salada de algas",
  "sekihan": "sekihan",
  "sel_roti": "sel roti",
  "selat_solo": "selat solo",
  "semla": "semla",
  "senate_bean_soup": "senate bean soup",
  "seolleongtang": "seolleongtang",
  "seri_muka": "seri muka",
  "serundeng": "serundeng",
  "sesame_chicken": "frango com gergelim",
  "sesame_seed_candy": "doce de gergelim",
  "seswaa": "seswaa",
  "seven_layer_salad": "seven-layer salad",
  "sfenj": "sfenj",
  "sfogliatella": "sfogliatella",
  "sfouf": "sfouf",
  "sgabeo": "sgabeo",
  "shab_deg": "shab deg",
  "shabu_shabu": "shabu-shabu",
  "shahan_ful": "shahan ful",
  "shahe_fen": "shahe fen",
  "shahi_paneer": "shahi paneer",
  "shaker_lemon_pie": "shaker lemon pie",
  "shakshouka": "shakshouka",
  "shami_kebab": "shami kebab",
  "shanghai_fried_noodles": "macarrão frito xangai",
  "shaobing": "shaobing",
  "shark_fin_soup": "shark fin soup",
  "shashlik": "shashlik",
  "shave_ice": "shave ice",
  "shaved_ice": "shaved ice",
  "shawarma": "shawarma",
  "shchi": "shchi",
  "she_crab_soup": "she-crab soup",
  "sheer_khurma": "sheer khurma",
  "sheftalia": "sheftalia",
  "shekerbura": "shekerbura",
  "shimotsukare": "shimotsuke",
  "shiokara": "shiokara",
  "shiro": "shiro",
  "shirred_egg": "ovo franzido",
  "shish_taouk": "shish taouk",
  "shkedei_marak": "shkedei marak",
  "shoofly_pie": "torta shoofly",
  "shortcake": "shortcake",
  "shrikhand": "shrikhand",
  "shrimp_and_grits": "camarão e grãos",
  "shrimp_creole": "camarão em crioulo",
  "shrimp_dejonghe": "camarão de jonghe",
  "shrimp_louie": "camarão louie",
  "shrimp_roe_noodles": "macarrão de camarão",
  "shuizhu": "shui zhu",
  "shumai": "shumai",
  "silver_needle_noodles": "silver needle noodles",
  "sincronizada": "sincronizada",
  "sinigang": "sinigang",
  "sinseollo": "sinseollo",
  "sirop_de_liege": "sirop de liège",
  "siu_yuk": "siu yuk",
  "skilandis": "skilandis",
  "skilpadjies": "skilpadjies",
  "sklandrausis": "sklandrausis",
  "skordalia": "skordalia",
  "slatko": "slatko",
  "slavink": "slavink",
  "slinger": "slinger",
  "sloppy_joe": "sloppy joe",
  "smalahove": "smalahove",
  "smazeny_syr": "smažený sýr",
  "smoked_meat": "smoked meat",
  "smore": "s'more",
  "smorgastarta": "smorgastarta",
  "smulpaj": "smulpaj",
  "smyrna_meatballs": "almôndegas de esmirna",
  "smørrebrød": "smørrebrød",
  "snack_cake": "bolo de lanche",
  "snickerdoodle": "snickerdoodle",
  "snickers_salad": "salada de snickers",
  "soan_papdi": "soan papdi",
  "soki": "soki",
  "solkadhi": "solkadhi",
  "solyanka": "solyanka",
  "sonofabitch_stew": "sonofabitch stew",
  "sonoran_hot_dog": "cachorro-quente de sonora",
  "sop_saudara": "sop saudara",
  "sopa_de_gato": "sopa de gato",
  "sopaipilla": "sopaipilla",
  "sope": "sopa",
  "sorbetes": "sorvete",
  "sorrel_soup": "sopa de azeda",
  "sosatie": "sosatie",
  "soto": "soto",
  "soto_ayam": "soto ayam",
  "soto_mie": "soto mie",
  "souffle": "suflê",
  "soup_alla_canavese": "sopa de canavese",
  "sour_cherry_soup": "sopa de cereja azeda",
  "souvlaki": "souvlaki",
  "soy_egg": "ovo cozido",
  "soy_sauce_chicken": "frango ao molho de soja",
  "soybean_sprout": "soybean sprout",
  "spaghetti": "espaguete",
  "spaghetti_aglio_e_olio": "espaguete ao alho e óleo",
  "spaghetti_alle_vongole": "espaguete ao vôngole",
  "spaghetti_bolognese": "esparguete à bolonhesa",
  "spaghetti_carbonara": "espaguete à carbonara",
  "spam_musubi": "spam musubi",
  "spanakopita": "spanakopita",
  "spanakorizo": "spanakorizo",
  "spanish_rice": "arroz espanhol",
  "spatzle": "spätzle",
  "speculaas": "speculaas",
  "spettekaka": "spettekaka",
  "spiedie": "spiedie",
  "spongata": "spongata",
  "sponge_cake": "pão de ló",
  "spoonbread": "pão de colher",
  "spotted_dick": "spotted dick",
  "spring_roll": "rolinho primavera",
  "squab": "squab",
  "squid": "lula",
  "squid_luau": "luau de lula",
  "squid_tongseng": "lula tongseng",
  "st_honore_cake": "torta saint honoré",
  "st_louis_style_pizza": "pizza estilo saint lois",
  "st_paul_sandwich": "sanduíche estilo saint paul",
  "stack_cake": "pilha de bolo",
  "stamppot": "stamppot",
  "steak": "bife",
  "steak_au_poivre": "filé au poivre",
  "steak_de_burgo": "filé de burgo",
  "steak_diane": "bife diane",
  "steak_sandwich": "sanduíche de bife",
  "steak_tartare": "steak tartare",
  "steamed_clams": "mariscos cozidos",
  "steamed_meatball": "almôndega cozidas",
  "stinky_tofu": "tofu fedido",
  "stir_fried_tomato_and_scrambled_eggs": "stirfried de tomate e ovos mexidos",
  "stoemp": "stoemp",
  "stottie_cake": "stottie cake",
  "stracciatella": "stracciatella",
  "strapacky": "strapacky",
  "strawberry": "morango",
  "strawberry_delight": "morango delight",
  "strawberry_shortcake": "strawberry shortcake",
  "strawberry_wedge": "strawberry wedge",
  "streusel": "streusel",
  "stromboli": "stromboli",
  "stroopwafel": "stroopwafel",
  "strudel": "strudel",
  "struffoli": "struffoli",
  "stuffed_cabbage": "repolho recheado",
  "stuffed_ham": "presunto recheado",
  "stuffed_peppers": "pimentões recheados",
  "stuffed_squash": "abóbora recheada",
  "stuffed_tomato": "tomate recheado",
  "suanla_chaoshou": "suanla chaoshou",
  "submarine_sandwich": "sanduíche submarino",
  "succotash": "succotash",
  "suckling_pig": "leitão assado",
  "suet_pudding": "suet pudding",
  "suimono": "suimono",
  "sukhdi": "sukhdi",
  "sukiyaki": "sukiyaki",
  "sultsina": "sultsina",
  "sulu_kofte": "sulu kofte",
  "suman": "suman",
  "sundae": "sundae",
  "sundubu_jjigae": "jjigae de sundubu",
  "sunnundallu": "sunnundallu",
  "surf_and_turf": "surf and turf",
  "sushi": "sushi",
  "sussex_pond_pudding": "pudim de lagoa de sussex",
  "sutarfeni": "sutarfeni",
  "suya": "suya",
  "svickova": "svickova",
  "sweet_and_sour_pork": "carne de porco agridoce",
  "sweet_potato_pie": "torta de batata doce",
  "sweet_potato_soup": "sopa de batata doce",
  "sweet_shells": "sweet shells",
  "swiss_roll": "rolo de bolo",
  "swiss_steak": "bife suíço",
  "swiss_wing": "swiss wing",
  "syllabub": "syllabub",
  "syrniki": "syrniki",
  "szaloncukor": "szaloncukor",
  "tabbouleh": "tabule",
  "taco": "taco",
  "tafelspitz": "tafelspitz",
  "tagliatelle": "tagliatelle",
  "tahini": "tahine",
  "tahri": "tahri",
  "tahu_goreng": "tofu frito",
  "tahu_sumedang": "tahu sumedang",
  "tahu_tek_tek": "tahu tek tek",
  "taiyaki": "taiyaki",
  "tajine": "tajine",
  "takikomi_gohan": "takikomi-gohan",
  "takoyaki": "takoyaki",
  "talo": "talo",
  "tamago_kake_gohan": "tamago kake gohan",
  "tamale": "pamonha",
  "tamale_pie": "torta de pamonha",
  "tamarillo": "tamarillo",
  "tandoori_chicken": "frango tandoori",
  "tangelo": "tangelo",
  "tanghulu": "tanghulu",
  "tangyuan": "tangyuan",
  "tantuni": "tantuni",
  "tapai": "tapai",
  "tapenade": "tapenade",
  "tapioca_pudding": "pudim de tapioca",
  "taquito": "taquito",
  "taralli": "taralli",
  "tarama": "tarama",
  "tarator": "tarator",
  "tarhana": "tarhana",
  "taro_dumpling": "bolinho de taro",
  "tart": "tart",
  "tarta_de_santiago": "bolo de santiago",
  "tarte_a_la_bouillie": "tarte à la bouillie",
  "tarte_tatin": "tarte tatin",
  "tartiflette": "tartiflette",
  "tatws_pum_munud": "tatws pum munud",
  "tavce_gravce": "tavče gravče",
  "tave_kosi": "tavë kosi",
  "tavern_sandwich": "sanduíche de taverna",
  "tea_egg": "ovo de chá",
  "tekkadon": "tekka don",
  "tekwan": "tekwan",
  "tempoyak": "tempoyak",
  "tempura": "tempurá",
  "tenderloin": "beef tenderloin",
  "teochew_porridge": "teochew porridge",
  "tepsi_baytinijan": "tepsi baytinijan",
  "terrine": "terrine",
  "tetrazzini": "tetrazzini",
  "teurgoule": "teurgoule",
  "texas_tommy": "texas tommy",
  "thai_fried_rice": "arroz frito tailandês",
  "thai_suki": "suki tailandês",
  "thalipeeth": "thalipeeth",
  "thapthim_krop": "thapthim krop",
  "tharid": "tharid",
  "thekua": "thekua",
  "thiakry": "thiakry",
  "thieboudienne": "thieboudienne",
  "thit_kho_tau": "thit kho tau",
  "thong_yip": "thong yip",
  "thukpa": "thukpa",
  "tilkut": "tilkut",
  "tinginys": "tinginys",
  "tipsy_cake": "bolo embriagado",
  "tiramisu": "tiramisu",
  "tirokafteri": "tirokafteri",
  "tiropita": "tiropita",
  "tlacoyo": "tlacoyo",
  "tlayuda": "tlayuda",
  "toad_in_the_hole": "toad in the hole",
  "toasted_ravioli": "ravióli frito",
  "tochitura": "tochitura",
  "tofu_skin_roll": "tofu skin roll",
  "tom_kha_kai": "tom kha kai",
  "tom_yum": "tom yum",
  "tomato": "tomate",
  "tomato_and_egg_soup": "sopa de tomate e ovo",
  "tomato_cherry_red": "tomate cereja vermelho",
  "tomato_compote": "compota de tomate",
  "tomato_heart": "tomate coração",
  "tomato_maroon": "tomato maroon",
  "tomato_not_ripened": "tomate verde",
  "tomato_yellow": "tomate amarelo",
  "tompouce": "tompouce",
  "tong_sui": "tong sui",
  "tongseng": "tongseng",
  "tonkatsu": "tonkatsu",
  "torricado": "torricado",
  "torta_caprese": "torta caprese",
  "torta_de_gazpacho": "torta de gaspacho",
  "torta_pasqualina": "torta pasqualina",
  "torta_tre_monti": "torta tre monti",
  "tortas_de_aceite": "tortas de aceite",
  "torte": "bolo",
  "tortell": "tortell",
  "tortellini": "tortellini",
  "tostada": "torrada",
  "totopo": "totopo",
  "tourin": "tourin",
  "toyga_soup": "sopa de toyga",
  "trdelnik": "trdelník",
  "treacle_tart": "treacle tart",
  "tres_leches_cake": "bolo três leches",
  "trifle": "trifle",
  "trinxat": "trinxat",
  "tripe": "tripa",
  "tripe_soup": "sopa de tripas",
  "tripes_a_la_mode_de_caen": "tripa ao modo caen",
  "truffade": "truffade",
  "tsoureki": "tsoureki",
  "tsukemono": "tsukemono",
  "tsukudani": "tsukudani",
  "tteok": "tteok",
  "tteokguk": "tteokguk",
  "tufahije": "tufahije",
  "tulumba": "tulumba",
  "tuna_casserole": "caçarola de atum",
  "tuna_fish_sandwich": "sanduíche de atum",
  "tuna_pot": "lata de atum",
  "tuna_tartare": "tartare de atum",
  "tuo_zaafi": "tuo zaafi",
  "turducken": "turducken",
  "turkey_devonshire": "turkey devonshire",
  "turo_rudi": "turo rudi",
  "turos_csusza": "túrós csusza",
  "turron": "turrón",
  "turtle_soup": "sopa de tartaruga",
  "tuwo_masara": "tuwo masara",
  "tuwo_shinkafa": "tuwo shinkafa",
  "twice_cooked_pork": "carne de porco cozida duas vezes",
  "udon": "udon",
  "ugali": "ugali",
  "uiro": "uiro",
  "ukha": "ukha",
  "ulam": "ulam",
  "umeboshi": "umeboshi",
  "umngqusho": "umngqusho",
  "unagi": "unagi",
  "upma": "upma",
  "upside_down_cake": "bolo de cabeça para baixo",
  "urap": "urap",
  "urnebes": "urnebes",
  "usal": "usal",
  "ustipci": "ustipci",
  "utica_greens": "utica greens",
  "vangibath": "vangibath",
  "vanillerostbraten": "vanillerostbraten",
  "vasilopita": "vasilopita",
  "vatrushka": "vatrushka",
  "veal": "vitela",
  "veal_cordon_bleu": "vitela a cordon bleu",
  "veal_orloff": "vitela de orloff",
  "veda_bread": "veda bread",
  "veggie_burger": "hambúrguer vegetariano",
  "vermicelli": "vermicelli",
  "vetkoek": "vetkoek",
  "vichyssoise": "vichyssoise",
  "victoria_sandwich": "victoria sandwich",
  "vinegret": "vinagrete",
  "vispipuuro": "vispipuuro",
  "vitello_tonnato": "vitela com molho de atum",
  "vlaai": "vlaai",
  "vol_au_vent": "vol au vent",
  "waakye": "waakye",
  "wachipa": "wachipa",
  "waffle": "waffle",
  "waldorf_pudding": "pudim waldorf",
  "waldorf_salad": "salada waldorf",
  "wallenbergare": "wallenbergare",
  "walnut": "noz",
  "wat": "wat",
  "watalappam": "watalappan",
  "watergate_salad": "salada watergate",
  "watermelon": "melancia",
  "welsh_cake": "bolo galês",
  "welsh_rarebit": "welsh rarebit",
  "wenchang_chicken": "wenchang chicken",
  "west_slavic_fermented_cereal_soups": "west slavic fermented cereal soup",
  "white_boiled_shrimp": "camarão branco cozido",
  "white_cut_chicken": "corte de frango branco",
  "white_rice": "arroz branco",
  "whoopie_pie": "whoopie pie",
  "wodzionka": "wodzianka",
  "woku": "woku",
  "wonton": "wonton",
  "wonton_noodles": "sopa de wonton",
  "wotou": "wotou",
  "wrap": "wrap",
  "xacuti": "xacuti",
  "xiaolongbao": "xiao long bao",
  "xoi": "xoi",
  "yahni": "yahni",
  "yaka_mein": "yaka mein",
  "yaki_udon": "yaki udon",
  "yakiniku": "yakiniku",
  "yakisoba": "yakisoba",
  "yakitori": "yakitori",
  "yaksik": "yaksik",
  "yam_khai_dao": "yam khai dao",
  "yangzhou_fried_rice": "arroz frito yangzhou",
  "yassa": "yassa",
  "yi_mein": "yi mein",
  "yin_si_juan": "yin si juan",
  "yin_yang_fish": "peixe yin yang",
  "yong_tau_foo": "yong tau foo",
  "youmian": "youmian",
  "youtiao": "youtiao",
  "yufka": "yufka",
  "yule_log": "yule log",
  "yusheng": "yusheng",
  "yuxiang": "yuxiang",
  "zaalouk": "zaalouk",
  "zagorski_strukli": "zagorski strukli",
  "zarangollo": "zarangollo",
  "zeeuwse_bolus": "zeeuwse bolus",
  "zelnik": "zelnik",
  "zemlovka": "zemlovka",
  "zganci": "zganci",
  "zhajiangmian": "zhajiangmian",
  "zhaliang": "zhaliang",
  "zhangcha_duck": "pato zhangcha",
  "ziti": "ziti",
  "zongzi": "zongzi",
  "zoni": "zōni",
  "zopf": "zopf",
  "zoque": "zoque",
  "zosui": "zosui",
  "zrazy": "zrazy",
  "zuppa_toscana": "zuppa toscana",
  "zurcher_geschnetzeltes": "zürcher geschnetzeltes",
  "zwetschgenkuchen": "bolo de ameixa",
  "æbleflæsk": "æbleflæsk",
  "øllebrød": "øllebrød",
};
